### ISSUE TITLE
Align

### ISSUE THREAD

**Issue by Igcorreia** [zikes/circle-menu#5]
I have am trying to align horizontal the items but it seams that the calculations forces to the items not be align. 

Any simple change to make this happen?

**Comment by zikes** [comment]
The intended purpose of the circle menu is to provide the menu items in a circular aligment.  There are no simple changes to achieve horizontal alignments.

**Comment by Igcorreia** [comment]
I didn't explain myself, what I mean was that the CIRCLES where misaligned horizontal.  By changing the line 49:
I removed the " - 1" and the circles align equally.
